language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t malgo1311/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true malgo1311/react-test npm test

after_success:
  - docker build -t malgo1311/multi-client ./client
  - docker build -t malgo1311/multi-nginx ./nginx
  - docker build -t malgo1311/multi-server ./server
  - docker build -t malgo1311/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push malgo1311/multi-client
  - docker push malgo1311/multi-nginx
  - docker push malgo1311/multi-server
  - docker push malgo1311/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-946146228745"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY